# Generated by Django 5.1.1 on 2024-09-15 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
